server:
  port: 80
logging:
  config: classpath:logback-spring.xml

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://112.124.27.31:3306/users?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: apm
    password: Huawei@2019
    driver-class-name: com.mysql.cj.jdbc.Driver
